# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  RAW_DATA_DIR: artifacts/raw
  RAW_DATA_FILEPATH: artifacts/raw/raw.csv
  MOD_DATA_DIR: artifacts/modified
  MOD_DATA_FILEPATH: artifacts/modified/modified.csv
  SPLIT_DATA_DIR: artifacts/split_data_dir
  TRAIN_DATA: artifacts/split_data_dir/train.csv
  TEST_DATA: artifacts/split_data_dir/test.csv
  MODEL_DIR: artifacts/models
  MODEL_FILEPATH: artifacts/models/model.joblib

SEPARATOR: ;
metrics_file: scores.json
params_file: params.json

 

source_url: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

